name: 检查全部插件

on:
  pull_request:
    paths:
      - 'addons/sourcemod/scripting/**/*.sp'
      - 'addons/sourcemod/scripting/**/*.inc'
    branches:
      - main
  push:
    paths:
      - 'addons/sourcemod/scripting/**/*.sp'
      - 'addons/sourcemod/scripting/**/*.inc'
    branches:
      - main
  workflow_dispatch:
    paths:
      - 'addons/sourcemod/scripting/**/*.sp'
      - 'addons/sourcemod/scripting/**/*.inc'
    branches:
      - main

jobs:
  build:
    name: 以 sm${{ matrix.sm_version }} 进行编译
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        sm_version:
          #- "1.9"
          #- "1.10"
          - "1.11"
          - "1.12"

    steps:
      - uses: actions/checkout@v3
      - name: 设置环境变量
        run: |
          echo "SCRIPTS_PATH=$GITHUB_WORKSPACE/addons/sourcemod/scripting" >> $GITHUB_ENV

      - name: 设置 SourcePawn 编译器 ${{ matrix.SM_VERSION }}
        uses: rumblefrog/setup-sp@master
        with:
          version: ${{ matrix.SM_VERSION }}

      - name: 编译插件
        run: |
          for file in *.sp
          do
            echo -e "\nCompiling $file..."
            spcomp -w234 -O2 -v2 -i $SCRIPTS_PATH/include $file
          done
        working-directory: ${{ env.SCRIPTS_PATH }}/